#override properties form main application.yml file

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true 
      path: /h2
  datasource:
    url: jdbc:h2:mem:smartinterviewdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa 
    password: sa
    driver-class-name: org.h2.Driver