spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartinterviewdb
    username: root
    password: root@lamp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    
 
#  profiles:
#    active:
#    - dev